name: Use Liquibase

on:
  workflow_dispatch:

jobs:
  use-liquibase:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: liquibase/setup-liquibase@v3
          with:
            version: '5.0.3'
            edition: 'community'
        - run: liquibase --version

        - name: Install PostgreSQL Driver
          run: liquibase lpm add postgresql --global
        
        - name: Run Database Migration
          run: liquibase update \
            --changelog-file=changelog.xml \
            --url=jdbc:postgresql://postgres-standalone.cuusbdloicfm.us-east-1.rds.amazonaws.com:5432/appdb \
            --username=postgres \
            --password=${{ secrets.DB_PASSWORD }}