name: Use Liquibase

on:
  workflow_dispatch:

jobs:
  use-liquibase:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: liquibase/setup-liquibase@v3
          with:
            version: '5.0.3'
            edition: 'community'
        - run: liquibase --version

        - name: Install PostgreSQL Driver
          run: liquibase lpm add postgresql --global
        
        - name: Run Database Migration
          env:
            LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres-standalone.cuusbdloicfm.us-east-1.rds.amazonaws.com:5432/appdb
            LIQUIBASE_COMMAND_USERNAME: postgres
            LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.DB_PASSWORD }}
            LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.xml
          run: liquibase update